app/urls.py
from django.urls import path, re_path
from . import views

app_name = 'app'

urlpatterns = [
    path('room/', views.RoomListView.as_view()),
    path('room/<pk>/', views.RoomDetailView.as_view()),
    path('desk/<pk>/', views.DeskView.as_view()),
    path('demographic_questionnaire/', views.QuestionnaireView.as_view()),
    path('analytics/', views.AnalyticsView.as_view()),
    path('alertness_interval/', views.AlertnessIntervalView.as_view()),
    path('alertness_questionnaire/', views.AlertnessQuestionnaireAnswerView.as_view()),
    path('demographic_questionnaire_answer/', views.QuestionnaireAnswerView.as_view()),
    path('register/', views.CreateParticipantView.as_view()),
    re_path(
        r'^participant/(?P<username>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$',
        views.ParticipantView.as_view()),
    re_path(
        r'^recommendation/(?P<username>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$',
        views.RecommendationView.as_view()),
    re_path(
        r'^category/(?P<username>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$',
        views.CategoryView.as_view()),
]

floor_plan/urls.py
from django.urls import path, re_path
from . import views

app_name = "floor_plan"

urlpatterns = [
    re_path(r'^room/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='room-detail'),
    re_path(r'^room/(?P<pk>[0-9]+)/delete/$', views.RoomDelete.as_view(), name='room-delete'),
    re_path(r'^$', views.sandbox, name='sandbox'),
    re_path(r'^add_user/$', views.WayanFormView.as_view(), name='person-add'),
    re_path(r'^android_add_user/$', views.RegisterAPI.as_view(), name='android-add'),
    re_path(r'^android_login/$', views.LoginAPI.as_view(), name='android-login'),
    re_path(r'^add_room/$', views.RoomCreate.as_view(), name='room-add'),
    re_path(r'^add_table/$', views.TableCreate.as_view(), name='table-add'),
    re_path(r'^add_chair/$', views.ChairCreate.as_view(), name='chair-add'),
    re_path(r'^add_window/$', views.WindowCreate.as_view(), name='window-add'),
]

app/models/room.py
from django.db import models


"""
Room models
"""


class Room(models.Model):

    """
    Represents a room in which experiments take place
    """

    name = models.CharField(max_length=250, unique=True)  # the name of the room

    def __str__(self):
        return self.name


class Side(models.Model):

    """
    An abstract class that represents one of four sides where an item can be placed
    """

    TOP = 1
    RIGHT = 2
    BOTTOM = 3
    LEFT = 4

    SIDES = (
        (TOP, 'Top'),
        (RIGHT, 'Right'),
        (BOTTOM, 'Bottom'),
        (LEFT, 'Left')
    )

    side = models.IntegerField(choices=SIDES)  # the side where the item is placed

    class Meta:
        abstract = True  # abstract class


class RoomItem(Side):

    """
    An abstract class that represents an item in the experiment room
    """

    margin = models.IntegerField()  # the margin from the room item side's corner as the origin
    length = models.IntegerField()  # the length of the room item

    class Meta:
        abstract = True  # abstract class


class Door(RoomItem):

    """
    Represents a door in the experiment room
    """

    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='door')  # the room the door is in

    def __str__(self):
        return 'Door (' + str(self.pk) + ') in room ' + str(self.room)


class Window(RoomItem):

    """
    Represents a window in the experiment room
    """

    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='window')  # the room the window is in

    def __str__(self):
        return 'Window (' + str(self.pk) + ') in room ' + str(self.room)


class Sensor(models.Model):

    """
    Represents a sensor
    """

    name = models.CharField(max_length=250, unique=True)  # the name of the sensor
    column = models.IntegerField()  # the column number of the sensor in the CSV file

    def __str__(self):
        return self.name + ' (column ' + str(self.column) + ')'


class Desk(Side):

    """
    Represents a desk in the experiment room
    """

    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='desk')  # the room the desk is in
    illuminance_sensor = models.ForeignKey(
        Sensor, on_delete=models.SET_NULL,
        related_name='illuminance_sensor',
        blank=True, null=True)  # the illuminance sensor at the desk
    occupancy_sensor = models.ForeignKey(
        Sensor, on_delete=models.SET_NULL,
        related_name='occupancy_sensor',
        blank=True, null=True)  # the occupancy sensor at the desk
    side = models.IntegerField(
        choices=Side.SIDES,
        verbose_name='chair side')  # the side at which the chair is placed
    pos_x = models.IntegerField()  # the x-coordinate of the desk in pixels
    pos_y = models.IntegerField()  # the y-coordinate of the desk in pixels
    illuminance = models.FloatField(default=0)  # the illuminance value measured at the desk
    occupied = models.BooleanField(default=False)  # the occupancy of the desk
    score = models.FloatField(default=0)  # used to recommend a desk

    def __str__(self):
        return 'Desk (' + str(self.pk) + ') in room ' + str(self.room)

    def recommended_desks(room, target_illuminance):

        """
        Returns the desks ordered according to the target illuminance
        """

        desks_in_room = Desk.objects.filter(room=room)

        for desk in desks_in_room:
            if desk.occupied:
                desks_in_room = desks_in_room.exclude(pk=desk.pk)
            desk.score = abs(target_illuminance - desk.illuminance)
            desk.save()

        return desks_in_room.order_by('score')


class SensorLog(models.Model):

    """
    Represents the values measured by sensors at a point in time
    """

    desk = models.ForeignKey(
        Desk,
        on_delete=models.CASCADE,
        related_name='sensor_log')  # the desk at which the values were measured
    timestamp = models.DateTimeField()  # the time at which the values were measured
    illuminance = models.FloatField()  # the illuminance value at the desk
    occupied = models.BooleanField(default=False)  # the occupancy of the desk

    def __str__(self):
        return str(self.desk) + ': ' + str(self.illuminance) + ' at ' + self.timestamp.strftime('%Y-%m-%d %H:%M:%S')

floor_plan/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Room(models.Model):
    code = models.CharField(max_length=10)
    x_length = models.IntegerField()
    y_length = models.IntegerField()

    def get_absolute_url(self):
        return reverse('floor_plan:sandbox')

    def __str__(self):
        return self.code


class Table(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    number = models.IntegerField()
    x_pos = models.IntegerField()
    y_pos = models.IntegerField()
    x_size = models.IntegerField()
    y_size = models.IntegerField()

    def get_absolute_url(self):
        return reverse('floor_plan:sandbox')

    def __str__(self):
        return 'Table ' + str(self.number)


class Chair(models.Model):
    table = models.ForeignKey(Table, on_delete=models.CASCADE)
    number = models.IntegerField()
    position = models.IntegerField()
    occupied = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('floor_plan:sandbox')

    def __str__(self):
        return 'Chair' + str(self.number)


class Sensor(models.Model):
    name = models.CharField(max_length=5)
    date = models.DateTimeField()
    value = models.FloatField()


class Window(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    start_pos = models.IntegerField()
    end_pos = models.IntegerField()

    def get_absolute_url(self):
        return reverse('floor_plan:room_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return 'Window from ' + str(self.start_pos) + ' to ' + str(self.end_pos)


class Participant(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    room = models.CharField(max_length=5)
    email_address = models.CharField(
        unique=True, max_length=250
    )

    def __str__(self):
        return str(self.user)


class Wayan(models.Model):
    email = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    loggedIn = models.BooleanField(default=False)

    def __str__(self):
        return self.email

floor_plan/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template import loader
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import CreateView, DeleteView
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from floor_plan.serializers import *
from .form import WayanForm
from .models import Room, Table, Chair, Window


def sandbox(request):
    all_rooms = Room.objects.all()
    template = loader.get_template('floor_plan/floorPlan.html')
    context = {
        'all_rooms': all_rooms,
    }
    return HttpResponse(template.render(context, request))


class RoomCreate(CreateView):
    model = Room
    fields = ['code', 'x_length', 'y_length']


class TableCreate(CreateView):
    model = Table
    fields = ['room', 'number', 'x_pos', 'y_pos', 'x_size', 'y_size']


class ChairCreate(CreateView):
    model = Chair
    fields = ['table', 'number', 'position', 'occupied']


class WindowCreate(CreateView):
    model = Window
    fields = ['room', 'start_pos', 'end_pos']


class DetailView(generic.DetailView):
    model = Room
    template_name = 'floor_plan/room_detail.html'


class RoomDelete(DeleteView):
    model = Room
    success_url = reverse_lazy('floor_plan:sandbox')


class RoomList(APIView):

    def get(self, request):
        rooms = Room.objects.all()
        serializer = RoomSerializer(rooms, many=True)
        return Response(serializer.data)

    def post(self):
        pass


class WayanFormView(View):
    form_class = WayanForm
    template_name = 'floor_plan/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user.save()

            user = authenticate(username=email, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('floor_plan:sandbox')

        return render(request, self.template_name, {'form': form})


class RegisterAPI(APIView):
    form_class = WayanForm

    def get(self, request):
        user = User.objects.all()
        serializer = WayanSerializer(user, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = WayanForm(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class LoginAPI(APIView):

    serializer_class = WayanLoginSerializer

    def post(self, request):
        serializer = WayanLoginSerializer(data=request.data)

        if serializer.is_valid():

            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    # def post(self, request, *args, **kwargs):
    #     return HttpResponse('This is POST request')

    # @api_view(['POST'])
    # def post(self, request):
    #     data = request.POST
    #     pretty_print_POST(prepared)
    #     form = UserForm(request.POST)
    #
    #     if form.is_valid():
    #         user = form.save(commit=False)
    #         email = form.cleaned_data['email']
    #         username = form.cleaned_data['username']
    #         password = form.cleaned_data['password']
    #         user.set_password(password)
    #         user.save()
    #
    #         user = authenticate(username=email, password=password)
    #         if user is not None:
    #             if user.is_active:
    #                 login(request, user)
    #                 return redirect('floor_plan:sandbox')

floor_plan/templates/floor_plan/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Luxify
        {% endblock %}
    </title>

     {% load staticfiles %}
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
     <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
     <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
{#    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />﻿#}


</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'floor_plan:sandbox' %}">Luxify</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">

                <!-- Room button -->
                <li class="{% block room_active %} {% endblock %}">
                    <a href="{% url 'floor_plan:room-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Room
                    </a>
                </li>

                <!-- Table button -->
                <li class="{% block table_active %} {% endblock %}">
                    <a href="{% url 'floor_plan:table-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Table
                    </a>
                </li>
                <li class="{% block chair_active %} {% endblock %}">
                    <a href="{% url 'floor_plan:chair-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Chair
                    </a>
                </li>

                <!-- Window button -->
                <li class="{% block window_active %} {% endblock %}">
                    <a href="{% url 'floor_plan:window-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Window
                    </a>
                </li>

                <!-- User button -->
		<li>
			<a href="{% url 'floor_plan:person-add' %}">
				<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; User
			</a>
		</li>
           </ul>
        </div>
    </div>
</nav>
    {% block body %}
    {% endblock %}
</body>
</html>

floor_plan/templates/floor_plan/chair_form.html
{% extends 'floor_plan/base.html' %}

<!-- Sets title to page -->
{% block title %}
    Create a new Room
{% endblock %}

<!-- Set "add chair" button to active in nav -->
{% block chair_active %}
    active
{% endblock %}

<!-- Beginning of black from base.html-->
{% block body %}

    {% include 'floor_plan/template-layout-form.html' %}

{% endblock %}

floor_plan/templates/floor_plan/floorPlan.html
{% extends 'floor_plan/base.html' %}

{% block body %}

<h1>Floor Plan</h1>
<ul>
   {% for room in all_rooms %}
        <li>
            <a href="{% url 'floor_plan:room-detail' room.id %}">
                {{ room }}
            </a>
            <ul>
               {% for table in room.table_set.all %}
                    <li>
                        {{ table }}
                        <ul>
                            {% for chair in table.chair_set.all %}
                                <li>
                                    {{ chair }}
                                </li>
                            {% endfor %}
                        </ul>
                        </li>
                {% endfor %}
                {% for window in room.window_set.all %}
                    <li>
                        {{ window }}
                    </li>
                {% endfor %}
            </ul>
        </li>
    {% endfor %}
</ul>

{% endblock %}

floor_plan/templates/floor_plan/registration_form.html
{% extends 'floor_plan/base.html' %}
{% block title %}
    Create a new User
{% endblock %}

{% block user_active %}
    active
{% endblock %}

{% block body %}

    {% include 'floor_plan/template-layout-form.html' %}

    <form action="{% url 'floor_plan:android-add' %}" method="post">
    </form>


{% endblock %}

floor_plan/templates/floor_plan/room_detail.html
{% extends 'floor_plan/base.html' %}

{% block title %}Album Details{% endblock %}

{% block body %}
    <ul class="nav navbar-nav navbar-right">
        <li>
            <form action="{% url 'floor_plan:room-delete' room.id %}" method="post" style="display: inline">
                <input type="hidden" name="next" value="{{ next }}" />
                <input type="hidden" name="room_id" value="{{ room.id }}">
                <button class="btn btn-primary" >
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Edit
                </button>
            </form>
            <form action="{% url 'floor_plan:room-delete' room.id %}" method="post" style="display: inline">
                <input type="hidden" name="next" value="{{ next }}" />
                <input type="hidden" name="room_id" value="{{ room.id }}">
                <button class="btn btn-danger" style="margin-right: 1.5em">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>&nbsp; Delete
                </button>
            </form>
        </li>
{#        <li>#}
{#            <a class="btn btn-primary" href="{% url 'floor_plan:room-update' room.id %}">#}
{#                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Edit#}
{#            </a>#}
{#        </li>#}
    </ul>
    <h1>{{ room.code }}</h1>
    <ul>
        {% for table in room.table_set.all %}
            <li>
                <a href="/">
                    {{ table.number }}
                </a>
                <br>
            </li>
        {% endfor %}
    </ul>


{% endblock %}

floor_plan/templates/floor_plan/room_form.html
{% extends 'floor_plan/base.html' %}
{% block title %}
    Create a new Room
{% endblock %}

{% block room_active %}
    active
{% endblock %}

{% block body %}

    {% include 'floor_plan/template-layout-form.html' %}

{% endblock %}

floor_plan/templates/floor_plan/table_form.html
{% extends 'floor_plan/base.html' %}
{% block title %}
    Create a new Table
{% endblock %}

{% block table_active %}
    active
{% endblock %}

{% block body %}
    {% include 'floor_plan/template-layout-form.html' %}
{% endblock %}

floor_plan/templates/floor_plan/window_form.html
{% extends 'floor_plan/base.html' %}
{% block title %}
    Create a new Window
{% endblock %}

{% block window_active %}
    active
{% endblock %}

{% block body %}

{% include 'floor_plan/template-layout-form.html' %}

{% endblock %}